#frontend/Containerfile

FROM public.ecr.aws/docker/library/node:20-slim

WORKDIR /app

COPY package*.json .

RUN npm ci
RUN npm cache clean --force

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev", "--", "-H", "0.0.0.0"]
